version: '3'

services:
  wallet_app:
    build: .
    depends_on:
      - wallet_mongodb
      - wallet_rabbitmq
    ports:
      - 3101:3101

  wallet_mongodb:
    image: mongo:4-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo_express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: wallet_mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo

  wallet_rabbitmq:
    image: rabbitmq:3-alpine
    hostname: wallet_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
